CREATE DATABASE MARQUEZA_C;
USE MARQUEZA_C;

CREATE TABLE T_PERSONA(
    PER_ID INT PRIMARY KEY AUTO_INCREMENT,
    PER_UUID VARCHAR(45) UNIQUE NOT NULL,
    PER_NOMBRE VARCHAR(100) NOT NULL,
    PER_SEG_NOMBRE VARCHAR(45) NULL,
    PER_PRI_APELLIDO VARCHAR(45) NULL,
    PER_SEG_APELLIDO VARCHAR(45) NULL,
    PER_CORREO VARCHAR(100) NOT NULL,
    PER_DIRECCION VARCHAR(45) NOT NULL,
    PER_IDENTIFICACION INT NOT NULL,
    PER_TELEFONO INT NOT NULL
);

CREATE TABLE T_CLIENTE(
    CLI_ID INT PRIMARY KEY AUTO_INCREMENT,
    CLI_UUID VARCHAR(45) UNIQUE NOT NULL,
    CLI_PER_ID INT NOT NULL
);

CREATE TABLE T_PROVEEDOR(
    PROV_ID INT PRIMARY KEY AUTO_INCREMENT,
    PROV_UUID VARCHAR(45) UNIQUE NOT NULL,
    PROV_PER_ID INT NOT NULL
);

ALTER TABLE T_CLIENTE ADD FOREIGN KEY (CLI_PER_ID) REFERENCES T_PERSONA(PER_ID);
ALTER TABLE T_PROVEEDOR ADD FOREIGN KEY (PROV_PER_ID) REFERENCES T_PERSONA(PER_ID);

CREATE TABLE T_USUARIOS(
    USUA_ID INT PRIMARY KEY AUTO_INCREMENT,
    USUA_UUID VARCHAR(45) UNIQUE NOT NULL,
    USUA_NOMBRE VARCHAR(60) NOT NULL,
    USUA_CORREO VARCHAR(100) NOT NULL,
    USUA_CONTRASENA VARCHAR(45) NOT NULL,
    USUA_ESTADO VARCHAR(45) NOT NULL,
    USUA_DET_ETC_ID INT NOT NULL
);

ALTER TABLE T_USUARIOS ADD FOREIGN KEY (USUA_DET_ETC_ID) REFERENCES T_DETALLES_ETC(DET_ETC_ID);

CREATE TABLE T_COTIZACIONES(
    COT_ID INT PRIMARY KEY AUTO_INCREMENT,
    COT_UUID VARCHAR(45) UNIQUE NOT NULL,
    COT_PRO_CODIGO VARCHAR(45) NOT NULL,
    COT_PRO_NOMBRE VARCHAR(45) NOT NULL,
    COT_CANTIDAD INT NOT NULL,
    COT_PRECIO INT NOT NULL,
    COT_TOTAL_PAGAR INT NOT NULL,
    COT_USUA_ID INT NOT NULL,
    COT_CLI_ID INT NOT NULL
);

ALTER TABLE T_COTIZACIONES ADD FOREIGN KEY (COT_USUA_ID) REFERENCES T_USUARIOS(USUA_ID);
ALTER TABLE T_COTIZACIONES ADD FOREIGN KEY (COT_CLI_ID) REFERENCES T_CLIENTE(CLI_ID);

CREATE TABLE T_VENTAS(
    VENT_ID INT PRIMARY KEY AUTO_INCREMENT,
    VENT_UUID VARCHAR(40) UNIQUE NOT NULL,
    VENT_FECHA DATE NOT NULL,
    VENT_USUA_ID INT NOT NULL,
    VENT_CLI_ID INT NOT NULL
);

ALTER TABLE T_VENTAS ADD FOREIGN KEY (VENT_USUA_ID) REFERENCES T_USUARIOS(USUA_ID);
ALTER TABLE T_VENTAS ADD FOREIGN KEY (VENT_CLI_ID) REFERENCES T_CLIENTE(CLI_ID);

CREATE TABLE T_PRODUCTOS(
    PROD_ID INT PRIMARY KEY AUTO_INCREMENT,
    PROD_UUID VARCHAR(45) UNIQUE NOT NULL,
    PROD_CODIGO VARCHAR(45) NOT NULL,
    PROD_NOMBRE VARCHAR(45) NOT NULL,
    PROD_CANTIDAD INT NOT NULL,
    PROD_PRECIO INT NOT NULL,
    PROD_ESTADO VARCHAR(45) NOT NULL,
    PROD_USUA_ID INT NOT NULL,
    PROD_DET_ETC_ID INT NOT NULL
);

ALTER TABLE T_PRODUCTOS ADD FOREIGN KEY (PROD_USUA_ID) REFERENCES T_USUARIOS(USUA_ID);
ALTER TABLE T_PRODUCTOS ADD FOREIGN KEY (PROD_DET_ETC_ID) REFERENCES T_DETALLES_ETC(DET_ETC_ID);

CREATE TABLE T_VENT_PROD(
    VENTPRO_ID INT PRIMARY KEY AUTO_INCREMENT,
    VENTPRO_UUID VARCHAR(45) UNIQUE NOT NULL,
    VENTPRO_CANTIDAD INT NOT NULL,
    VENTPRO_VENT_ID INT NOT NULL,
    VENTPRO_PROD_ID INT NOT NULL
);

ALTER TABLE T_VENT_PROD ADD FOREIGN KEY (VENTPRO_VENT_ID) REFERENCES T_VENTAS(VENT_ID);
ALTER TABLE T_VENT_PROD ADD FOREIGN KEY (VENTPRO_PROD_ID) REFERENCES T_PRODUCTOS(PROD_ID);

CREATE TABLE T_CONTACTO(
    CONT_ID INT PRIMARY KEY AUTO_INCREMENT,
    CONT_UUID VARCHAR(45) UNIQUE NOT NULL,
    CONT_TIPO_DATO VARCHAR(15) NOT NULL,
    CONT_CONTENIDO VARCHAR(45) NOT NULL,
    CONT_PROV_ID INT NOT NULL
);

ALTER TABLE T_CONTACTO ADD FOREIGN KEY (CONT_PROV_ID) REFERENCES T_PROVEEDOR(PROV_ID);

CREATE TABLE T_INSUMOS(
    INS_ID INT PRIMARY KEY AUTO_INCREMENT,
    INS_UUID VARCHAR(45) UNIQUE NOT NULL,
    INS_CODIGO VARCHAR(45) NOT NULL,
    INS_NOMBRE VARCHAR(45) NOT NULL,
    INS_CANTIDAD INT NOT NULL,
    INS_PRECIO INT NOT NULL,
    INS_ESTADO VARCHAR(45) NOT NULL,
    INS_USUA_ID INT NOT NULL,
    INS_DET_ETC_ID INT NOT NULL,
    INS_PROV_ID INT NOT NULL
);

ALTER TABLE T_INSUMOS ADD FOREIGN KEY (INS_USUA_ID) REFERENCES T_USUARIOS(USUA_ID);
ALTER TABLE T_INSUMOS ADD FOREIGN KEY (INS_DET_ETC_ID) REFERENCES T_DETALLES_ETC(DET_ETC_ID);
ALTER TABLE T_INSUMOS ADD FOREIGN KEY (INS_PROV_ID) REFERENCES T_PROVEEDOR(PROV_ID);

CREATE TABLE T_PRODU_INSUM(
    PRODINSU_ID INT PRIMARY KEY AUTO_INCREMENT,
    PRODINSU_UUID VARCHAR(45) UNIQUE NOT NULL,
    PRODINSU_CANTIDAD INT NOT NULL,
    PRODINSU_PROD_ID INT NOT NULL,
    PRODINSU_INS_ID INT NOT NULL
);

ALTER TABLE T_PRODU_INSUM ADD FOREIGN KEY (PRODINSU_PROD_ID) REFERENCES T_PRODUCTOS(PROD_ID);
ALTER TABLE T_PRODU_INSUM ADD FOREIGN KEY (PRODINSU_INS_ID) REFERENCES T_INSUMOS(INS_ID);

CREATE TABLE T_DETALLES_ETC(
    DET_ETC_ID INT PRIMARY KEY AUTO_INCREMENT,
    DET_ETC_UUID VARCHAR(45) UNIQUE NOT NULL,
    DET_ETC_NOMBRE VARCHAR(45) NOT NULL,
    DET_ETC_ETC_ID INT NOT NULL,
    DET_ETC_PER_ID INT NOT NULL
);

ALTER TABLE T_DETALLES_ETC ADD FOREIGN KEY (DET_ETC_ETC_ID) REFERENCES T_ESTADOS_TIPOS_CATEGORIAS(ETC_ID);
ALTER TABLE T_DETALLES_ETC ADD FOREIGN KEY (DET_ETC_PER_ID) REFERENCES T_PERSONA(PER_ID);

CREATE TABLE T_ESTADOS_TIPOS_CATEGORIAS(
    ETC_ID INT PRIMARY KEY AUTO_INCREMENT,
    ETC_UUID VARCHAR(45) UNIQUE NOT NULL,
    ETC_NOMBRE VARCHAR(45) NOT NULL
);