-- MySQL Script generated by MySQL Workbench
-- Tue Aug 25 14:39:22 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema MARQUEZA_C
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `MARQUEZA_C` ;

-- -----------------------------------------------------
-- Schema MARQUEZA_C
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MARQUEZA_C` DEFAULT CHARACTER SET utf8 ;
USE `MARQUEZA_C` ;

-- -----------------------------------------------------
-- Table `MARQUEZA_C`.`T_ESTADO_TIPOS_CATEGORIAS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MARQUEZA_C`.`T_ESTADO_TIPOS_CATEGORIAS` ;

CREATE TABLE IF NOT EXISTS `MARQUEZA_C`.`T_ESTADO_TIPOS_CATEGORIAS` (
  `ETC_ID` INT NOT NULL AUTO_INCREMENT COMMENT 'valor único asignado a cada registro (fila) de una tabla. Su función principal es distinguir de manera inequívoca cada elemento, sin importar si otros datos (como nombres o direcciones) se repiten',
  `ETC_UUID` VARCHAR(40) NOT NULL COMMENT 'código alfanumérico de 36 caracteres dividida por guioneslos UUID son aleatorios. Esto evita que un usuario pueda deducir o adivinar la cantidad total de registros',
  `ETC_NOMBRE` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ETC_ID`),
  UNIQUE INDEX `ETC_UUID_UNIQUE` (`ETC_UUID` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MARQUEZA_C`.`T_PERSONA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MARQUEZA_C`.`T_PERSONA` ;

CREATE TABLE IF NOT EXISTS `MARQUEZA_C`.`T_PERSONA` (
  `PER_ID` INT NOT NULL AUTO_INCREMENT,
  `PER_UUID` VARCHAR(45) NOT NULL,
  `PER_NOMBRE` VARCHAR(100) NOT NULL,
  `PER_SEG_NOMBRE` VARCHAR(45) NULL,
  `PER_PRI_APELLIDO` VARCHAR(45) NULL,
  `PER_SEG_APELLIDO` VARCHAR(45) NULL,
  `PER_CORREO` VARCHAR(100) NOT NULL,
  `PER_DIRECCION` VARCHAR(45) NOT NULL,
  `PER_IDENTIFICACION` INT NOT NULL,
  `PER_TELEFONO` INT NOT NULL,
  PRIMARY KEY (`PER_ID`),
  UNIQUE INDEX `PER_UUID_UNIQUE` (`PER_UUID` ASC) ,
  UNIQUE INDEX `PER_IDENTIFICACION_UNIQUE` (`PER_IDENTIFICACION` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MARQUEZA_C`.`T_DETALLES_ETC`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MARQUEZA_C`.`T_DETALLES_ETC` ;

CREATE TABLE IF NOT EXISTS `MARQUEZA_C`.`T_DETALLES_ETC` (
  `DET_ETC_ID` INT NOT NULL AUTO_INCREMENT COMMENT 'valor único asignado a cada registro (fila) de una tabla. Su función principal es distinguir de manera inequívoca cada elemento, sin importar si otros datos (como nombres o direcciones) se repiten',
  `DET_ETC_UUID` VARCHAR(40) NOT NULL COMMENT 'código alfanumérico de 36 caracteres dividida por guioneslos UUID son aleatorios. Esto evita que un usuario pueda deducir o adivinar la cantidad total de registros',
  `DET_ETC_NOMBRE` VARCHAR(45) NOT NULL,
  `DET_ETC_ETC_ID` INT NOT NULL,
  `DET_ETC_PER_ID` INT NOT NULL,
  PRIMARY KEY (`DET_ETC_ID`),
  UNIQUE INDEX `DET_ETC_UUID_UNIQUE` (`DET_ETC_UUID` ASC) ,
  INDEX `fk_T_DETALLES_ETC_T_ESTADO_TIPOS_CATEGORIAS1_idx` (`DET_ETC_ETC_ID` ASC) ,
  INDEX `fk_T_DETALLES_ETC_T_PERSONA1_idx` (`DET_ETC_PER_ID` ASC) ,
  CONSTRAINT `fk_T_DETALLES_ETC_T_ESTADO_TIPOS_CATEGORIAS1`
    FOREIGN KEY (`DET_ETC_ETC_ID`)
    REFERENCES `MARQUEZA_C`.`T_ESTADO_TIPOS_CATEGORIAS` (`ETC_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_T_DETALLES_ETC_T_PERSONA1`
    FOREIGN KEY (`DET_ETC_PER_ID`)
    REFERENCES `MARQUEZA_C`.`T_PERSONA` (`PER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MARQUEZA_C`.`T_USUARIOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MARQUEZA_C`.`T_USUARIOS` ;

CREATE TABLE IF NOT EXISTS `MARQUEZA_C`.`T_USUARIOS` (
  `USUA_ID` INT NOT NULL AUTO_INCREMENT COMMENT 'valor único asignado a cada registro (fila) de una tabla. Su función principal es distinguir de manera inequívoca cada elemento, sin importar si otros datos (como nombres o direcciones) se repiten.\n\n',
  `USUA_UUID` VARCHAR(40) NOT NULL COMMENT 'código alfanumérico de 36 caracteres dividida por guioneslos UUID son aleatorios. Esto evita que un usuario pueda deducir o adivinar la cantidad total de registros ',
  `USUA_NOMBRE` VARCHAR(60) NOT NULL COMMENT 'contiene el numero de identificacion del usuario la sea cedula de ciudadania o algun otro documento que acredite su identidad',
  `USUA_CORREO` VARCHAR(100) NOT NULL,
  `USUA_CONTRASEÑA` VARCHAR(45) NOT NULL COMMENT 'es la contraseña del usuario con la cual obtiene acceso a la base de datos para modificar su contenido',
  `USUA_ESTADO` VARCHAR(45) NOT NULL,
  `USUA_DET_ETC_ID` INT NOT NULL,
  PRIMARY KEY (`USUA_ID`),
  UNIQUE INDEX `USUA_UUID_UNIQUE` (`USUA_UUID` ASC) ,
  INDEX `fk_T_USUARIOS_T_DETALLES_ETC1_idx` (`USUA_DET_ETC_ID` ASC) ,
  CONSTRAINT `fk_T_USUARIOS_T_DETALLES_ETC1`
    FOREIGN KEY (`USUA_DET_ETC_ID`)
    REFERENCES `MARQUEZA_C`.`T_DETALLES_ETC` (`DET_ETC_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MARQUEZA_C`.`T_PRODUCTOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MARQUEZA_C`.`T_PRODUCTOS` ;

CREATE TABLE IF NOT EXISTS `MARQUEZA_C`.`T_PRODUCTOS` (
  `PROD_ID` INT NOT NULL AUTO_INCREMENT COMMENT 'valor único asignado a cada registro (fila) de una tabla. Su función principal es distinguir de manera inequívoca cada elemento, sin importar si otros datos (como nombres o direcciones) se repiten',
  `PROD_UUID` VARCHAR(40) NOT NULL COMMENT 'código alfanumérico de 36 caracteres dividida por guioneslos UUID son aleatorios. Esto evita que un usuario pueda deducir o adivinar la cantidad total de registros',
  `PROD_CODIGO` VARCHAR(45) NOT NULL,
  `PROD_NOMBRE` VARCHAR(45) NOT NULL,
  `PROD_CANTIDAD` INT NOT NULL,
  `PROD_PRECIO` INT NOT NULL,
  `PROD_ESTADO` VARCHAR(45) NOT NULL,
  `PROD_USUA_ID` INT NOT NULL,
  `PROD_DET_ETC_ID` INT NOT NULL,
  PRIMARY KEY (`PROD_ID`),
  UNIQUE INDEX `PROD_UUID_UNIQUE` (`PROD_UUID` ASC) ,
  UNIQUE INDEX `PROD_CODIGO_UNIQUE` (`PROD_CODIGO` ASC) ,
  INDEX `fk_T_PRODUCTOS_T_USUARIO1_idx` (`PROD_USUA_ID` ASC) ,
  INDEX `fk_T_PRODUCTOS_T_DETALLES_ETC1_idx` (`PROD_DET_ETC_ID` ASC) ,
  CONSTRAINT `fk_T_PRODUCTOS_T_USUARIO1`
    FOREIGN KEY (`PROD_USUA_ID`)
    REFERENCES `MARQUEZA_C`.`T_USUARIOS` (`USUA_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_T_PRODUCTOS_T_DETALLES_ETC1`
    FOREIGN KEY (`PROD_DET_ETC_ID`)
    REFERENCES `MARQUEZA_C`.`T_DETALLES_ETC` (`DET_ETC_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MARQUEZA_C`.`T_PROVEEDORES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MARQUEZA_C`.`T_PROVEEDORES` ;

CREATE TABLE IF NOT EXISTS `MARQUEZA_C`.`T_PROVEEDORES` (
  `PROV_ID` INT NOT NULL AUTO_INCREMENT COMMENT 'valor único asignado a cada registro (fila) de una tabla. Su función principal es distinguir de manera inequívoca cada elemento, sin importar si otros datos (como nombres o direcciones) se repiten',
  `PROV_UUID` VARCHAR(40) NOT NULL COMMENT 'código alfanumérico de 36 caracteres dividida por guioneslos UUID son aleatorios. Esto evita que un usuario pueda deducir o adivinar la cantidad total de registros',
  `PROV_PER_ID` INT NOT NULL,
  PRIMARY KEY (`PROV_ID`),
  UNIQUE INDEX `PROV_UUID_UNIQUE` (`PROV_UUID` ASC) ,
  INDEX `fk_T_PROVEEDORES_T_PERSONA1_idx` (`PROV_PER_ID` ASC) ,
  CONSTRAINT `fk_T_PROVEEDORES_T_PERSONA1`
    FOREIGN KEY (`PROV_PER_ID`)
    REFERENCES `MARQUEZA_C`.`T_PERSONA` (`PER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MARQUEZA_C`.`T_INSUMOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MARQUEZA_C`.`T_INSUMOS` ;

CREATE TABLE IF NOT EXISTS `MARQUEZA_C`.`T_INSUMOS` (
  `INS_ID` INT NOT NULL AUTO_INCREMENT COMMENT 'valor único asignado a cada registro (fila) de una tabla. Su función principal es distinguir de manera inequívoca cada elemento, sin importar si otros datos (como nombres o direcciones) se repiten',
  `INS_UUID` VARCHAR(40) NOT NULL,
  `INS_CODIGO` VARCHAR(45) NOT NULL,
  `INS_NOMBRE` VARCHAR(45) NOT NULL,
  `INS_CANTIDAD` INT NOT NULL,
  `INS_PRECIO` INT NOT NULL,
  `INS_ESTADO` VARCHAR(45) NOT NULL,
  `INS_USUA_ID` INT NOT NULL,
  `INS_PROV_ID` INT NOT NULL,
  `INS_DET_ETC_ID` INT NOT NULL,
  PRIMARY KEY (`INS_ID`),
  UNIQUE INDEX `INS_UUID_UNIQUE` (`INS_UUID` ASC) ,
  UNIQUE INDEX `INS_CODIGO_UNIQUE` (`INS_CODIGO` ASC) ,
  INDEX `fk_T_INSUMOS_T_USUARIO1_idx` (`INS_USUA_ID` ASC) ,
  INDEX `fk_T_INSUMOS_T_PROVEEDORES1_idx` (`INS_PROV_ID` ASC) ,
  INDEX `fk_T_INSUMOS_T_DETALLES_ETC1_idx` (`INS_DET_ETC_ID` ASC) ,
  CONSTRAINT `fk_T_INSUMOS_T_USUARIO1`
    FOREIGN KEY (`INS_USUA_ID`)
    REFERENCES `MARQUEZA_C`.`T_USUARIOS` (`USUA_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_T_INSUMOS_T_PROVEEDORES1`
    FOREIGN KEY (`INS_PROV_ID`)
    REFERENCES `MARQUEZA_C`.`T_PROVEEDORES` (`PROV_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_T_INSUMOS_T_DETALLES_ETC1`
    FOREIGN KEY (`INS_DET_ETC_ID`)
    REFERENCES `MARQUEZA_C`.`T_DETALLES_ETC` (`DET_ETC_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MARQUEZA_C`.`T_CLIENTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MARQUEZA_C`.`T_CLIENTE` ;

CREATE TABLE IF NOT EXISTS `MARQUEZA_C`.`T_CLIENTE` (
  `CLI_ID` INT NOT NULL AUTO_INCREMENT COMMENT 'valor único asignado a cada registro (fila) de una tabla. Su función principal es distinguir de manera inequívoca cada elemento, sin importar si otros datos (como nombres o direcciones) se repiten',
  `CLI_UUID` VARCHAR(40) NOT NULL COMMENT 'código alfanumérico de 36 caracteres dividida por guioneslos UUID son aleatorios. Esto evita que un usuario pueda deducir o adivinar la cantidad total de registros',
  `CLI_PER_ID` INT NOT NULL,
  PRIMARY KEY (`CLI_ID`),
  UNIQUE INDEX `CLI_UUID_UNIQUE` (`CLI_UUID` ASC) ,
  INDEX `fk_T_CLIENTE_T_PERSONA1_idx` (`CLI_PER_ID` ASC) ,
  CONSTRAINT `fk_T_CLIENTE_T_PERSONA1`
    FOREIGN KEY (`CLI_PER_ID`)
    REFERENCES `MARQUEZA_C`.`T_PERSONA` (`PER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MARQUEZA_C`.`T_VENTAS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MARQUEZA_C`.`T_VENTAS` ;

CREATE TABLE IF NOT EXISTS `MARQUEZA_C`.`T_VENTAS` (
  `VENT_ID` INT NOT NULL AUTO_INCREMENT COMMENT 'valor único asignado a cada registro (fila) de una tabla. Su función principal es distinguir de manera inequívoca cada elemento, sin importar si otros datos (como nombres o direcciones) se repiten',
  `VENT_UUID` VARCHAR(40) NOT NULL COMMENT 'código alfanumérico de 36 caracteres dividida por guioneslos UUID son aleatorios. Esto evita que un usuario pueda deducir o adivinar la cantidad total de registros',
  `VENT_FECHA` DATE NOT NULL,
  `VENT_USUA_ID` INT NOT NULL,
  `VENT_CLI_ID` INT NOT NULL,
  PRIMARY KEY (`VENT_ID`),
  UNIQUE INDEX `VENT_UUID_UNIQUE` (`VENT_UUID` ASC) ,
  INDEX `fk_T_VENTAS_T_USUARIO_idx` (`VENT_USUA_ID` ASC) ,
  INDEX `fk_T_VENTAS_T_CLIENTE1_idx` (`VENT_CLI_ID` ASC) ,
  CONSTRAINT `fk_T_VENTAS_T_USUARIO`
    FOREIGN KEY (`VENT_USUA_ID`)
    REFERENCES `MARQUEZA_C`.`T_USUARIOS` (`USUA_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_T_VENTAS_T_CLIENTE1`
    FOREIGN KEY (`VENT_CLI_ID`)
    REFERENCES `MARQUEZA_C`.`T_CLIENTE` (`CLI_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MARQUEZA_C`.`T_VENT_PROD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MARQUEZA_C`.`T_VENT_PROD` ;

CREATE TABLE IF NOT EXISTS `MARQUEZA_C`.`T_VENT_PROD` (
  `VENPRO_ID` INT NOT NULL AUTO_INCREMENT COMMENT 'valor único asignado a cada registro (fila) de una tabla. Su función principal es distinguir de manera inequívoca cada elemento, sin importar si otros datos (como nombres o direcciones) se repiten',
  `VENPRO_UUID` VARCHAR(40) NOT NULL COMMENT 'código alfanumérico de 36 caracteres dividida por guioneslos UUID son aleatorios. Esto evita que un usuario pueda deducir o adivinar la cantidad total de registros',
  `VENPRO_CANTIDAD` INT NOT NULL,
  `VENPRO_VENT_ID` INT NOT NULL,
  `VENPRO_PROD_ID` INT NOT NULL,
  INDEX `fk_T_VENT_PROD_T_VENTAS1_idx` (`VENPRO_VENT_ID` ASC) ,
  INDEX `fk_T_VENT_PROD_T_PRODUCTOS1_idx` (`VENPRO_PROD_ID` ASC) ,
  PRIMARY KEY (`VENPRO_ID`),
  UNIQUE INDEX `VENPRO_UUID_UNIQUE` (`VENPRO_UUID` ASC) ,
  CONSTRAINT `fk_T_VENT_PROD_T_VENTAS1`
    FOREIGN KEY (`VENPRO_VENT_ID`)
    REFERENCES `MARQUEZA_C`.`T_VENTAS` (`VENT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_T_VENT_PROD_T_PRODUCTOS1`
    FOREIGN KEY (`VENPRO_PROD_ID`)
    REFERENCES `MARQUEZA_C`.`T_PRODUCTOS` (`PROD_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MARQUEZA_C`.`T_COTIZACIONES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MARQUEZA_C`.`T_COTIZACIONES` ;

CREATE TABLE IF NOT EXISTS `MARQUEZA_C`.`T_COTIZACIONES` (
  `COT_ID` INT NOT NULL AUTO_INCREMENT COMMENT 'valor único asignado a cada registro (fila) de una tabla. Su función principal es distinguir de manera inequívoca cada elemento, sin importar si otros datos (como nombres o direcciones) se repiten',
  `COT_UUID` VARCHAR(40) NOT NULL COMMENT 'código alfanumérico de 36 caracteres dividida por guioneslos UUID son aleatorios. Esto evita que un usuario pueda deducir o adivinar la cantidad total de registros ',
  `COT_PRO_CODIGO` VARCHAR(45) NOT NULL,
  `COT_PRO_NOMBRE` VARCHAR(45) NOT NULL,
  `COT_PRO_CANTIDAD` INT NOT NULL,
  `COT_PRO_PRECIO` INT NOT NULL,
  `COT_TOTAL_PAGAR` INT NOT NULL,
  `COT_USUA_ID` INT NOT NULL,
  `COT_CLI_ID` INT NOT NULL,
  PRIMARY KEY (`COT_ID`),
  UNIQUE INDEX `COT_UUID_UNIQUE` (`COT_UUID` ASC) ,
  INDEX `fk_T_COTIZACIONES_T_USUARIO1_idx` (`COT_USUA_ID` ASC) ,
  INDEX `fk_T_COTIZACIONES_T_CLIENTE1_idx` (`COT_CLI_ID` ASC) ,
  CONSTRAINT `fk_T_COTIZACIONES_T_USUARIO1`
    FOREIGN KEY (`COT_USUA_ID`)
    REFERENCES `MARQUEZA_C`.`T_USUARIOS` (`USUA_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_T_COTIZACIONES_T_CLIENTE1`
    FOREIGN KEY (`COT_CLI_ID`)
    REFERENCES `MARQUEZA_C`.`T_CLIENTE` (`CLI_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MARQUEZA_C`.`T_PRODU_INSUM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MARQUEZA_C`.`T_PRODU_INSUM` ;

CREATE TABLE IF NOT EXISTS `MARQUEZA_C`.`T_PRODU_INSUM` (
  `PROINSU_ID` INT NOT NULL AUTO_INCREMENT COMMENT 'valor único asignado a cada registro (fila) de una tabla. Su función principal es distinguir de manera inequívoca cada elemento, sin importar si otros datos (como nombres o direcciones) se repiten',
  `PROINSU_UUID` VARCHAR(40) NOT NULL COMMENT 'código alfanumérico de 36 caracteres dividida por guioneslos UUID son aleatorios. Esto evita que un usuario pueda deducir o adivinar la cantidad total de registros',
  `PROINSU_CANTIDAD` INT NOT NULL,
  `PROINSU_PROD_ID` INT NOT NULL,
  `PROINSU_INS_ID` INT NOT NULL,
  PRIMARY KEY (`PROINSU_ID`),
  UNIQUE INDEX `PROINSU_UUID_UNIQUE` (`PROINSU_UUID` ASC) ,
  INDEX `fk_PRODU_ISUM_T_PRODUCTOS1_idx` (`PROINSU_PROD_ID` ASC) ,
  INDEX `fk_PRODU_ISUM_T_INSUMOS1_idx` (`PROINSU_INS_ID` ASC) ,
  CONSTRAINT `fk_PRODU_ISUM_T_PRODUCTOS1`
    FOREIGN KEY (`PROINSU_PROD_ID`)
    REFERENCES `MARQUEZA_C`.`T_PRODUCTOS` (`PROD_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRODU_ISUM_T_INSUMOS1`
    FOREIGN KEY (`PROINSU_INS_ID`)
    REFERENCES `MARQUEZA_C`.`T_INSUMOS` (`INS_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MARQUEZA_C`.`T_CONTACTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MARQUEZA_C`.`T_CONTACTO` ;

CREATE TABLE IF NOT EXISTS `MARQUEZA_C`.`T_CONTACTO` (
  `CONT_ID` INT NOT NULL AUTO_INCREMENT COMMENT 'valor único asignado a cada registro (fila) de una tabla. Su función principal es distinguir de manera inequívoca cada elemento, sin importar si otros datos (como nombres o direcciones) se repiten',
  `CONT_UUID` VARCHAR(40) NOT NULL COMMENT 'código alfanumérico de 36 caracteres dividida por guioneslos UUID son aleatorios. Esto evita que un usuario pueda deducir o adivinar la cantidad total de registros',
  `CONT_TIPO_DATO` VARCHAR(15) NOT NULL,
  `CONT_CONTENIDO` VARCHAR(45) NOT NULL,
  `CONT_PROV_ID` INT NOT NULL,
  PRIMARY KEY (`CONT_ID`),
  UNIQUE INDEX `CONT_UUID_UNIQUE` (`CONT_UUID` ASC) ,
  INDEX `fk_T_CONTACTO_T_PROVEEDORES1_idx` (`CONT_PROV_ID` ASC) ,
  CONSTRAINT `fk_T_CONTACTO_T_PROVEEDORES1`
    FOREIGN KEY (`CONT_PROV_ID`)
    REFERENCES `MARQUEZA_C`.`T_PROVEEDORES` (`PROV_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
